name = leaky
depends = mesecons
optional_depends = moreblocks
description = Leaky Nodes look like standard blocks, but you can walk through them (directly or make nodes disappear with Mesecons).
title = Leaky
author = mmm-sued
