name = leaky
depends = mesecons
optional_depends = moreblocks
description = Leaky nodes look like standard blocks, but you can walk through them (directly or using Mesecons switch).
title = Leaky
author = mmm-sued
