name = leaky
depends = mesecons
optional_depends = moreblocks
description = Leaky-Nodes sehen aus wie Standardblöcke, man kann aber durch sie hindurchgehen (direkt oder per Mese-Schaltung).
title = Leaky
author = mmm-sued